import React from "react";
import styles from '../styles/experience.module.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';
import '@fortawesome/fontawesome-svg-core/styles.css';



const Experience=()=>{
    return(
        <>
        <div className={styles.exper_container}>
           <div className={styles.firstContainer}>
               <h2>Get your free trial now!</h2>
               <p>Best Online CRM Software Dubai, UAE</p>
               <button>GET FREE TRIAL<FontAwesomeIcon icon={faArrowRight} style={{ marginLeft: "10px" }}></FontAwesomeIcon></button>
           </div>
           <div className={styles.secondContainer}>
                <div className={styles.secondinnerConatiner}>
                     <div className={styles.contentdiv}>
                         <h2>Essential CRM Reports for Driving Sales</h2>
                         <p>According to the User Role and the accessibility given by the Admin, the Marketing coordinator and managers can view the reports and performance of each sales executive and evaluate how they were capable to handle and convert each leads to an opportunity that leads to a final sale. You can get a quick overview of all customers and the products that they have purchased from you.</p>
                         <p>Get a quick review of all the product sale patterns throughout the year. Also, manage your expenses and income generated by the marketing team to enhance your profits and efficiency in the market. With the help of CRM Software in Dubai, you can have an edge over your competitors by providing better customer service to your customers and clients.</p>
                         <p>
                         Get reports on:
                         </p>
                         <ul>
                            <li>Inquiry Report</li>
                            <li>Performance of each salesman</li>
                            <li>User Activities</li>
                            <li>Closed Details</li>
                            <li>Login Hours of each user. (Only Admin can view this)</li>

                         </ul>
                     </div>
                     <div className={styles.imagediv}>
                         <img src={require('../image/exper1.webp')} alt="exper1image"/>
                     </div>
                </div>



                <div className={styles.secondinnerConatiner}>
                     <div className={styles.imagediv}>
                         <img src={require('../image/exper2.webp')} alt="exper1image"/>
                     </div>
                     <div className={styles.contentdiv}>
                         <h2>Master Management in Elate CRM</h2>
                         <p>This feature can be accessible only by the admin and the manager. With this, you can configure all the products that you sell, the number of employees that are working for you, create salesmen login ids along with their credentials.</p>
                         <p>Masters give you access to all the core modules and features of the CRM Abu Dhabi and help you configure the details of your company. As ELATE CRM is a cloud application you can access it from all places and get quick information about your business when needed. Get information on all the expenses that are done in the organization and manage the production or services accordingly.</p>
                     </div>
                </div>


                <div className={styles.secondinnerConatiner}>
                     <div className={styles.contentdiv}>
                         <h2>Setting</h2>
                         <ul>
                            <li>Only the admin user will have the privilege to close one inquiry</li>
                            <li>User security control</li>
                            <li>Admin user will have the privilege to check login report</li>
                            <li>Admin users will have the right to take backup</li>
                         </ul>
                         <p>Elate CRM is an award-winning CRM software in UAE. Generate more leads and close sales faster. A 100% cloud-based CRM in Dubai, Abu Dhabi, Sharjah- Request a Free Demo.</p>
                         <p>Elate CRM - Cloud CRM Software in Dubai, Ajman, UAE for businesses. Best CRM Software in UAE. Top CRM Software in Dubai, Ajman, UAE with sales automation</p>
                     </div>
                     <div className={styles.imagediv}>
                         <img src={require('../image/exper3.webp')} alt="exper1image"/>
                     </div>
                </div>
           </div>
        </div>
        </>
    )
}


export default Experience;